version: '3.8'

# Configuration de développement avec optimisations
services:
  trading:
    build:
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      - ../.pip_cache:/root/.cache/pip  # Cache pip persistant
      - ../trading:/app/trading  # Hot reload du code
    environment:
      - PYTHONUNBUFFERED=1
      - COMPOSE_DOCKER_CLI_BUILD=1
      - DOCKER_BUILDKIT=1
      - PYTHONMALLOC=malloc
      - MALLOC_TRIM_THRESHOLD_=100000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    command: redis-server --save 60 1 --loglevel warning --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 512M

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  tensorboard:
    volumes:
      - ../logs:/logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 1G

volumes:
  redis_data:
  grafana_data:
