# Configuration du modèle hybride

# Configuration CNN
cnn:
  architecture: "resnet"  # resnet, inception, efficientnet
  input_shape: [100, 10]  # [time_steps, features]
  filters: [32, 64, 128]
  kernel_sizes: [3, 3, 3]
  strides: [1, 1, 1]
  padding: "same"
  activation: "relu"
  dropout_rate: 0.2
  l2_reg: 0.01
  attention_heads: 4
  attention_dim: 64

# Configuration GNA
gna:
  population_size: 100
  generations: 50
  mutation_rate: 0.1
  crossover_rate: 0.8
  elite_size: 5
  tournament_size: 3
  risk_weight: 0.3
  performance_weight: 0.7
  min_risk_threshold: 0.1
  max_risk_threshold: 0.3

# Configuration de l'optimisation continue
optimization:
  update_frequency: 86400  # 24 heures en secondes
  min_samples: 1000
  validation_split: 0.2
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  momentum: 0.9
  early_stopping_patience: 10
  min_delta: 0.001
  max_optimization_time: 3600
  performance_threshold: 0.1
  risk_threshold: 0.2
  adaptation_threshold: 0.15

# Configuration de la détection d'anomalies
anomaly_detection:
  isolation_forest_contamination: 0.1
  z_score_threshold: 3.0
  autoencoder_latent_dim: 32
  reconstruction_threshold: 0.1
  min_samples_for_training: 1000

# Configuration des métriques avancées
metrics:
  risk_free_rate: 0.02
  confidence_level: 0.95
  rolling_window: 252
  min_trades: 10
  max_drawdown_threshold: 0.2

# Configuration de l'analyse des sentiments et volatilité
sentiment_volatility:
  window_size: 86400  # 24 heures en secondes
  min_samples: 100
  confidence_threshold: 0.7
  sentiment_threshold: 0.3
  volatility_threshold: 0.2
  max_sequence_length: 100
  embedding_dim: 100
  lstm_units: 64
  dense_units: 32
  dropout_rate: 0.2
  learning_rate: 0.001
  batch_size: 32
  epochs: 50
  early_stopping_patience: 10
  min_delta: 0.001

# Configuration du prétraitement des données
preprocessing:
  sequence_length: 100
  train_split: 0.7
  validation_split: 0.15
  test_split: 0.15
  min_samples: 1000
  feature_scaling: "standard"  # standard, minmax, robust
  target_scaling: "standard"
  fill_method: "ffill"  # ffill, bfill, interpolate
  remove_outliers: true
  outlier_threshold: 3.0

# Configuration de la sauvegarde et restauration
save_restore:
  checkpoint_dir: "checkpoints"
  model_dir: "models"
  backup_dir: "backups"
  max_checkpoints: 5
  save_frequency: 3600  # 1 heure en secondes
  compression: true
  versioning: true 