# Configuration de la gestion des risques
version: '1.0'

# Configuration globale des risques
global:
  # Capital maximum à risquer en pourcentage
  max_risk_per_trade: 0.01  # 1% du capital
  # Capital maximum à risquer par jour
  max_daily_risk: 0.05  # 5% du capital
  # Capital maximum à risquer par semaine
  max_weekly_risk: 0.15  # 15% du capital
  # Exposition maximale totale
  max_total_exposure: 0.5  # 50% du capital

# Configuration des risques par classe d'actifs
asset_classes:
  crypto:
    max_exposure: 0.3  # 30% du capital
    max_position_size: 0.1  # 10% du capital
    max_leverage: 10
    correlation_threshold: 0.7
    volatility_threshold: 0.05  # 5%
    min_volume: 1000000  # Volume minimum en USDT
  
  forex:
    max_exposure: 0.4  # 40% du capital
    max_position_size: 0.05  # 5% du capital
    max_leverage: 20
    correlation_threshold: 0.8
    volatility_threshold: 0.02  # 2%
    min_volume: 5000000  # Volume minimum en unité de base
  
  stocks:
    max_exposure: 0.6  # 60% du capital
    max_position_size: 0.15  # 15% du capital
    max_leverage: 2
    correlation_threshold: 0.6
    volatility_threshold: 0.03  # 3%
    min_volume: 500000  # Volume minimum en unité de base

# Configuration des métriques de risque
metrics:
  # Métriques standard
  standard:
    sharpe_ratio:
      enabled: true
      min_threshold: 1.5
      period: 30
      risk_free_rate: 0.02  # 2%
    
    sortino_ratio:
      enabled: true
      min_threshold: 2.0
      period: 30
      risk_free_rate: 0.02  # 2%
    
    max_drawdown:
      enabled: true
      max_threshold: 0.2  # 20%
      period: 30
    
    value_at_risk:
      enabled: true
      confidence_level: 0.95
      period: 30
      max_threshold: 0.05  # 5%
  
  # Métriques personnalisées
  custom:
    risk_adjusted_return:
      enabled: true
      formula: "(return - risk_free_rate) / volatility"
      parameters:
        risk_free_rate: 0.02
        volatility_period: 30
      min_threshold: 1.0
    
    volume_weighted_price:
      enabled: true
      formula: "sum(price * volume) / sum(volume)"
      parameters:
        period: 20
      min_threshold: 0.0
    
    momentum_risk:
      enabled: true
      formula: "current_price / sma(price, period) - 1"
      parameters:
        period: 14
      max_threshold: 0.1

# Configuration des risques temporels
time_based_risk:
  # Périodes de trading à haut risque
  high_risk_periods:
    - name: "News économiques"
      reduction_factor: 0.5
      times:
        - start: "08:25"
          end: "08:35"
          days: [1, 2, 3, 4, 5]  # Lundi à Vendredi
    - name: "Ouverture US"
      reduction_factor: 0.7
      times:
        - start: "13:25"
          end: "13:35"
          days: [1, 2, 3, 4, 5]
  
  # Périodes de trading à faible risque
  low_risk_periods:
    - name: "Session asiatique"
      increase_factor: 1.2
      times:
        - start: "00:00"
          end: "08:00"
          days: [1, 2, 3, 4, 5]

# Configuration des corrélations
correlations:
  # Vérification des corrélations entre positions
  check_position_correlation: true
  # Période de calcul des corrélations
  correlation_period: 30
  # Seuil de corrélation maximum entre positions
  max_correlation: 0.7
  # Groupes d'actifs corrélés
  correlated_groups:
    crypto_majors:
      - BTC/USDT
      - ETH/USDT
      max_exposure: 0.2  # 20% du capital
    stable_coins:
      - USDC/USDT
      - BUSD/USDT
      max_exposure: 0.1  # 10% du capital

# Configuration des alertes de risque
risk_alerts:
  # Alertes de dépassement de seuil
  threshold_alerts:
    capital_utilization:
      enabled: true
      threshold: 0.8  # 80% du capital utilisé
    drawdown:
      enabled: true
      threshold: 0.1  # 10% de drawdown
    exposure:
      enabled: true
      threshold: 0.7  # 70% d'exposition
  
  # Alertes de changement de volatilité
  volatility_alerts:
    sudden_increase:
      enabled: true
      threshold: 2.0  # 2x la volatilité normale
      period: 10
    sustained_high:
      enabled: true
      threshold: 1.5  # 1.5x la volatilité normale
      period: 30

# Configuration des rapports de risque
risk_reporting:
  # Fréquence des rapports
  frequency: 3600  # En secondes (1 heure)
  # Métriques à inclure dans les rapports
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - exposure
    - correlation
  # Format des rapports
  format: 
    - json
    - csv
  # Destination des rapports
  destination:
    - file
    - email
  # Chemin de sauvegarde des rapports
  save_path: "reports/risk"