meta_learning:
  pre_training:
    instruments: ['BTC/USDT', 'ETH/USDT', 'BNB/USDT']
    epochs: 50
    batch_size: 32
  fine_tuning:
    learning_rate: 0.0001
    epochs: 10

neat:
  population_size: 50
  fitness_threshold: 0.95
  reset_on_extinction: False
  activation_options: ["relu", "sigmoid", "tanh"]

gan:
  latent_dim: 100
  generator:
    layers: [128, 256, 512]
    dropout: 0.3
  discriminator:
    layers: [512, 256, 128]
    dropout: 0.3

training:
  use_synthetic_data: True
  synthetic_samples: 1000
  evolve_architecture: True
  architecture_evolution_frequency: 100 